web_app/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField("Post")

web_app/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from web_app import db
from web_app.models import Post
from web_app.posts.forms import PostForm

posts = Blueprint("posts", __name__)

@posts.route("/new/post", methods=['GET', 'POST']) # show this html and allow http requests
@login_required # import function that makes the user required to be logged in
def new_post():
    form = PostForm() # creating new object from the forms.py's postform Class
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user) # create a DB entry with the data following
        db.session.add(post)
        db.session.commit()
        flash(f"Post has been successfully created", "success") # this is a Bootstrap thing
        return redirect(url_for('main.index'))
    return render_template('create_post.html', title='New Post', form=form, legend="New Post")

@posts.route("/post/<int:post_id>") # getting a variable from a DB, in this case the ID of the post
def post(post_id):
    post = Post.query.get_or_404(post_id) #creating a object from a database variable, if no post return template 404
    return render_template("post.html", title=post.title, post=post)

@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id): # MODIFY POST
    post = Post.query.get_or_404(post_id)
    if post.author != current_user: # check if the user want to modify is the author
        abort(403)
    form = PostForm()
    if form.validate_on_submit(): # insert into DB
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash(f"Post has been successfully modified", "success") # this is a Bootstrap thing
        return redirect(url_for('main.index'))
    elif request.method == "GET":
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update post', form=form, legend="Update Post")

@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id): #DELETE POST
    post = Post.query.get_or_404(post_id)
    if post.author != current_user: # check if the user want to modify is the author
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash(f"Post has been successfully deleted", "alert")
    return redirect(url_for('main.index'))

web_app/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from web_app import db, bcrypt
from web_app.models import User, Post
from web_app.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from web_app.users.utils import save_picture, send_reset_email

users = Blueprint("users", __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data)
        user = User(username=form.username.data,email=form.email.data,password=hashed_pw)
        db.session.add(user)
        db.session.commit()
        flash(f"Account created for {form.username.data}!", "success")
        return redirect(url_for('users.login'))
    return render_template('register.html', title="Register", form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            bcrypt
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for("main.index"))
        else:
            flash("No.","danger")
    return render_template('login.html', title="Login", form=form)

@users.route("/logout")
def logout():
        if current_user.is_authenticated:
            logout_user()
            return redirect(url_for("main.index"))


@users.route("/account", methods=['GET', 'POST'])
@login_required # calls the login_required decorator (function)
def account(): # this is the func that the base html for_url calls
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Your account has been updated!", "success")
        return redirect(url_for("users.account"))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for("static", filename="profile_pics/" + current_user.image_file)
    return render_template('account.html', title="Your Account", image_file=image_file, form = form)


@users.route("/user/<string:username>") # dynamic url from a variable
def user_posts(username):
    page = request.args.get("page", 1, type=int) # get the first page when index loads
    user = User.query.filter_by(username=username).first_or_404() # query the User DB and get the first item
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=2) # DB QUERY, object creation and setting up pages, and ordering by latest post
    return render_template('user_posts.html', posts=posts, user=user)



@users.route("/reset_password", methods=['GET', 'POST']) # this is the password reset request page, where you put in your email
def reset_request():
    if current_user.is_authenticated: # check if a pw reset request is valid (user not logged in already)
        return redirect(url_for("main.index"))
    form = RequestResetForm() # if valid, creates request reset form object and pass it to the html
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash("Check your email inbox", "info")
        return redirect(url_for("main.index"))
    return render_template('reset_request.html', title="Reset Password", form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST']) # creates a dynamic url based on a token
def reset_token(token):
    if current_user.is_authenticated: 
        return redirect(url_for("main.index"))
    user = User.verify_reset_token(token) # this is a function in the models.py, the actual token generation and user check
    if user is None:
        flash("Invalid token", 'warning')
        return redirect(url_for("users.reset_request"))
    form = ResetPasswordForm() # if token is right, creates a reset password form object
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data)
        user.password = hashed_pw
        db.session.commit()
        flash(f"Your password has been updated!", "success")
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title="Reset Password", form=form)



@users.route("/admin")
def admin():
    return render_template('admin.html',title="Admin page")

web_app/templates/account.html
{% extends "base.html" %}

{% block content %}
    <div class="content-section" >
        <div class="media" >
            <img class="rounded-circle account-img" src="{{ image_file }}" >
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
                <br>
            </div>
        </div>
        <form method="POST", action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form">
                <legend class="border-bottom mb-4">Account information</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                            </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                            </div>
                    {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{form.picture.label() }} <br>
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                                <span class="text-danger"> {{ error }} </span>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
        </form>     
    </div>
{% endblock content %}

web_app/templates/admin.html
{% extends "base.html" %}



{% block content %}
    <h1>Hi, {{ user.username }}, please log in!</h1>

{% endblock %}

web_app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">FLASK</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.index') }}">Home</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                <a class="nav-item nav-link text-danger" href="{{ url_for('users.account') }}"> {{current_user.username}}</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

web_app/templates/create_post.html
{% extends "base.html" %}

{% block content %}

    <div class="content-section">
        <form method="POST", action="">
            {{ form.hidden_tag() }}
            <fieldset class="form">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                            </div>
                    {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.content.label(class="form-control-label") }}
                    {% if form.content.errors %}
                        {{ form.content(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                            </div>
                    {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
        </form>     
    </div>


{% endblock content %}

web_app/templates/db.html
{% extends "base.html" %}

{%block content%}
<table>
{% for user in users %}

    <tr>
        <td>{{user.username}} </td>
        <td>{{user.email}} </td>
        <td>{{user.password}} </td>
    </tr>



{% endfor %}
</table>
{% endblock content %}

web_app/templates/index.html
{% extends "base.html" %}

{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{url_for("users.user_posts", username=post.author.username)}}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
              {% if post.author.username == current_user.username %}
                <a button type="button" class="btn btn-primary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}"> Edit </a>
                <a button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal" href="{{ url_for('posts.delete_post', post_id=post.id) }}"> Delete </a>
              {% endif %}
            </div>
            <h2> <a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}"> {{ post.title }} </a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        <!-- Modal -->
</article>

    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete post</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Delete post?
          </div>
          <div class="modal-footer">
            <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
              <input class="btn btn-danger" type="submit" value="Delete">
            </form>
             
            
          </div>
        </div>
      </div>
    </div>
    
    

{% endfor %}

{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2)  %}
  {% if page_num %}
    {% if posts.page == page_num%}
        <a class="btn btn-info media-body mb-4" href="{{ url_for("main.index", page=page_num) }}"> {{ page_num}} </a>
    {% else %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for("main.index", page=page_num) }}"> {{ page_num}} </a>
    {% endif %}
  {% else %}
    ...
  {% endif %}

{% endfor %}

{% endblock %}

web_app/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Flask Blog - {{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Flask Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="/">Home</a>
              <a class="nav-item nav-link" href="/about">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="/login">Login</a>
              <a class="nav-item nav-link" href="/register">Register</a>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

web_app/templates/login.html
{% extends "base.html" %}



{% block content %}
    <div class="content-section">
        <form method="POST", action="">
            {{ form.hidden_tag() }}
            <fieldset class="form">
                <legend class="border-bottom mb-4">Log in!</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                            </div>
                    {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                            </div>
                    {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                    <div class="form-check">
                        {{ form.remember(class="form-check-input")}}                       {{ form.remember(class="form-check-input")}}
                        {{ form.remember.label(class="form-check-label")}}
                    </div>
            </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
                <small class="text-muted ml-2">
                    <a href="{{url_for('users.reset_request')}}"> Forgot password?</a>
                </small>
        </form>     
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            No account? <a class="ml-2" href="{{url_for('users.register') }}"> Register here </a>
        </small>
    </div>


{% endblock content %}

web_app/templates/post.html
{% extends "base.html" %}

{% block content %}
    <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
        <div class="article-metadata">
        <a class="mr-2" href="#">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        </div>
        <h2 class="article-title"> {{ post.title }} </h2>
        <p class="article-content">{{ post.content }}</p>
    </div>
    </article>
{% endblock content %}

web_app/templates/reset_request.html
{% extends "base.html" %}

{% block content %}
    <div class="content-section">
        <form method="POST", action="">
            {{ form.hidden_tag() }}
            <fieldset class="form">
                <legend class="border-bottom mb-4">Reset password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                            </div>
                    {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
        </form>     
    </div>



{% endblock content %}

web_app/templates/user_posts.html
{% extends "base.html" %}

{% block content %}

<h1 class="mb-3"> Posts by {{ user.username }} ({{ posts.total }}) </h1>
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{url_for("users.user_posts", username=post.author.username)}}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
              {% if post.author.username == current_user.username %}
                <a button type="button" class="btn btn-primary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}"> Edit </a>
                <a button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal" href="{{ url_for('posts.delete_post', post_id=post.id) }}"> Delete </a>
              {% endif %}
            </div>
            <h2> <a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}"> {{ post.title }} </a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        <!-- Modal -->
</article>

    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete post</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Delete post?
          </div>
          <div class="modal-footer">
            <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
              <input class="btn btn-danger" type="submit" value="Delete">
            </form>
             
            
          </div>
        </div>
      </div>
    </div>
    
    

{% endfor %}
<!-- PAGINATION-->
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2)  %}
  {% if page_num %}
    {% if posts.page == page_num%}
        <a class="btn btn-info media-body mb-4" href="{{ url_for("users.user_posts", username=user.username, page=page_num) }}"> {{ page_num}} </a>
    {% else %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for("users.user_posts", username=user.username, page=page_num) }}"> {{ page_num}} </a>
    {% endif %}
  {% else %}
    ...
  {% endif %}

{% endfor %}

{% endblock %}